




import React, { useMemo } from 'react';
import { Step } from '../types';
import { STORY_CARDS } from '../data/storyCards';
import { determineJobSetupDetails } from '../utils';
import { SpecialRuleBlock } from './SpecialRuleBlock';
import { useTheme } from './ThemeContext';
import { useGameState } from '../hooks/useGameState';
import { STEP_IDS, CHALLENGE_IDS } from '../constants';

interface JobStepProps {
  step: Step;
}

export const JobStep: React.FC<JobStepProps> = ({ step }) => {
  const { gameState } = useGameState();
  const overrides = step.overrides || {};
  const activeStoryCard = STORY_CARDS.find(c => c.title === gameState.selectedStoryCard) || STORY_CARDS[0];
  const stepId = step.data?.id || step.id;
  const { theme } = useTheme();
  const isDark = theme === 'dark';
  const { isCampaign } = gameState;
  
  const { 
    contacts, 
    messages, 
    showStandardContactList, 
    isSingleContactChoice,
    cardsToDraw,
    totalJobCards
  } = useMemo(() => 
    determineJobSetupDetails(gameState, activeStoryCard, overrides),
    [gameState, activeStoryCard, overrides]
  );
  
  const { smugglersBluesSetup, lonelySmugglerSetup, sharedHandSetup } = activeStoryCard.setupConfig || {};

  const activeChallenges = useMemo(() => 
    activeStoryCard.challengeOptions?.filter(
      opt => gameState.challengeOptions[opt.id]
    ) || [], 
  [activeStoryCard.challengeOptions, gameState.challengeOptions]);

  const cardBg = isDark ? 'bg-black/60' : 'bg-white';
  const cardBorder = isDark ? 'border-zinc-800' : 'border-gray-200';
  const textColor = isDark ? 'text-gray-200' : 'text-gray-800';
  const pillBg = isDark ? 'bg-zinc-800' : 'bg-gray-100';
  const pillText = isDark ? 'text-gray-300' : 'text-gray-900';
  const pillBorder = isDark ? 'border-zinc-700' : 'border-gray-300';
  const dividerBorder = isDark ? 'border-zinc-800' : 'border-gray-200';
  const noteText = isDark ? 'text-gray-400' : 'text-gray-700';

  return (
    <div className="space-y-4">
      {isCampaign && (
        <SpecialRuleBlock source="story" title="Campaign Rules: Jobs & Contacts">
          <p>For each Contact you were Solid with at the end of the last game, remove 2 of your completed Jobs from play.</p>
          <p className="mt-2">Keep any remaining completed Jobs; you begin the game <strong>Solid with those Contacts</strong>.</p>
        </SpecialRuleBlock>
      )}

      {stepId.includes(STEP_IDS.D_RIM_JOBS) && (
        <SpecialRuleBlock source="setupCard" title="Rim Space Jobs">
            <p><strong>Rebuild the Contact Decks</strong> using <em>only</em> cards from the Blue Sun and Kalidasa expansions.</p>
        </SpecialRuleBlock>
      )}

      {sharedHandSetup && (
          <SpecialRuleBlock source="story" title="Story Override">
                <p>
                    Place <strong>one Job from each Contact</strong> face up on top of its deck. 
                    These face up Jobs form a shared hand of Inactive Jobs that everyone may use.
                </p>
          </SpecialRuleBlock>
      )}

      {/* Render all messages generated by the logic function */}
      {messages.map((msg, idx) => (
        <SpecialRuleBlock key={idx} source={msg.source} title={msg.title}>
          {msg.content}
        </SpecialRuleBlock>
      ))}

      {/* Render the standard contact list UI if needed */}
      {showStandardContactList && (
        <div className={`${cardBg} p-6 rounded-lg border ${cardBorder} shadow-sm transition-colors duration-300`}>
          {isSingleContactChoice ? (
            <>
              <p className={`mb-4 font-bold ${textColor} text-lg`}>Choose 1 Contact from the available list:</p>
              <div className="flex flex-wrap gap-2 mb-4">
                {contacts.map(contact => (
                  <span key={contact} className={`px-3 py-1 ${pillBg} ${pillText} rounded-full text-sm border ${pillBorder} shadow-sm font-bold`}>
                    {contact}
                  </span>
                ))}
              </div>
              <p className={`text-lg font-bold ${isDark ? 'text-amber-400' : 'text-amber-800'} mb-2`}>
                Draw {cardsToDraw || 3} Job Cards from your chosen contact.
              </p>
            </>
          ) : (
            <>
              <p className={`mb-4 font-bold ${textColor} text-lg`}>Draw 1 Job Card from each:</p>
              <div className="flex flex-wrap gap-2 mb-4">
                {contacts.map(contact => (
                  <span key={contact} className={`px-3 py-1 ${pillBg} ${pillText} rounded-full text-sm border ${pillBorder} shadow-sm font-bold`}>
                    {contact}
                  </span>
                ))}
              </div>
            </>
          )}
          <p className={`text-sm ${noteText} border-t ${dividerBorder} pt-3 mt-2 italic`}>
            Discard any unwanted jobs. {totalJobCards > 3 && !isSingleContactChoice && <span>Keep a hand of <strong>up to three</strong> Job Cards.</span>}
          </p>
        </div>
      )}

      {/* Render other special rules that are independent of job draw logic */}
      {activeChallenges.length > 0 && !messages.some(m => m.title === 'Challenge Active') && (
        <SpecialRuleBlock source="warning" title="Story Directives (Challenges)">
          <ul className="list-disc ml-5 space-y-1 text-sm">
            {activeChallenges.map(opt => <li key={opt.id}>{opt.label}</li>)}
          </ul>
          <p className="mt-2 text-xs italic opacity-80">These restrictions apply throughout the game.</p>
        </SpecialRuleBlock>
      )}

      {smugglersBluesSetup && (
        <SpecialRuleBlock source="story" title="Story Override">
          Place a $2000 bill under Amnon Duul, Patience, Badger, and Niska's Contact Decks.
        </SpecialRuleBlock>
      )}

      {lonelySmugglerSetup && (
        <SpecialRuleBlock source="story" title="Story Override">
          Place a <strong>Goal Token</strong> on the Contact Decks for <strong>Amnon Duul, Patience, Badger, and Niska</strong>.
        </SpecialRuleBlock>
      )}

      {activeStoryCard.setupConfig?.removePiracyJobs && (
        <SpecialRuleBlock source="story" title="Story Override">
          Pull all remaining Piracy Jobs from the Contact Decks and discard them. Reshuffle.
        </SpecialRuleBlock>
      )}
    </div>
  );
};
